/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vesalainen_comm_channel_winx_WinSerialChannel_SerialOutputStream */

#ifndef _Included_org_vesalainen_comm_channel_winx_WinSerialChannel_SerialOutputStream
#define _Included_org_vesalainen_comm_channel_winx_WinSerialChannel_SerialOutputStream
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
