/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vesalainen_comm_channel_linux_LinuxSerialChannel */

#ifndef _Included_org_vesalainen_comm_channel_linux_LinuxSerialChannel
#define _Included_org_vesalainen_comm_channel_linux_LinuxSerialChannel
#ifdef __cplusplus
extern "C" {
#endif
#undef org_vesalainen_comm_channel_linux_LinuxSerialChannel_VERSION
#define org_vesalainen_comm_channel_linux_LinuxSerialChannel_VERSION 1L
#ifdef __cplusplus
}
#endif
#endif
