/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vesalainen_comm_channel_winx_WinSerialChannel_SerialInputStream */

#ifndef _Included_org_vesalainen_comm_channel_winx_WinSerialChannel_SerialInputStream
#define _Included_org_vesalainen_comm_channel_winx_WinSerialChannel_SerialInputStream
#ifdef __cplusplus
extern "C" {
#endif
#undef org_vesalainen_comm_channel_winx_WinSerialChannel_SerialInputStream_MAX_SKIP_BUFFER_SIZE
#define org_vesalainen_comm_channel_winx_WinSerialChannel_SerialInputStream_MAX_SKIP_BUFFER_SIZE 2048L
#ifdef __cplusplus
}
#endif
#endif
