/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_vesalainen_comm_channel_WinSerialChannel */

#ifndef _Included_org_vesalainen_comm_channel_WinSerialChannel
#define _Included_org_vesalainen_comm_channel_WinSerialChannel
#ifdef __cplusplus
extern "C" {
#endif
#undef org_vesalainen_comm_channel_WinSerialChannel_MaxSelectors
#define org_vesalainen_comm_channel_WinSerialChannel_MaxSelectors 64L
#undef org_vesalainen_comm_channel_WinSerialChannel_VERSION
#define org_vesalainen_comm_channel_WinSerialChannel_VERSION 8L
#undef org_vesalainen_comm_channel_WinSerialChannel_MAXDWORD
#define org_vesalainen_comm_channel_WinSerialChannel_MAXDWORD -1L
#undef org_vesalainen_comm_channel_WinSerialChannel_EV_RXCHAR
#define org_vesalainen_comm_channel_WinSerialChannel_EV_RXCHAR 1L
#undef org_vesalainen_comm_channel_WinSerialChannel_MaxSelect
#define org_vesalainen_comm_channel_WinSerialChannel_MaxSelect 64L
/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    doClearBuffers
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_doClearBuffers
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    staticInit
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_staticInit
  (JNIEnv *, jclass);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    doConfigure
 * Signature: (JIIIIIZ)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_doConfigure
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint, jboolean);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    version
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_version
  (JNIEnv *, jobject);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    doOpen
 * Signature: ([B)J
 */
JNIEXPORT jlong JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_doOpen
  (JNIEnv *, jobject, jbyteArray);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    doRead
 * Signature: (JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_doRead
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    doWrite
 * Signature: (JLjava/nio/ByteBuffer;)I
 */
JNIEXPORT jint JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_doWrite
  (JNIEnv *, jobject, jlong, jobject);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    setDebug
 * Signature: (Z)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_setDebug
  (JNIEnv *, jclass, jboolean);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    doEnumPorts
 * Signature: (Ljava/util/List;)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_doEnumPorts
  (JNIEnv *, jclass, jobject);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    doClose
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_doClose
  (JNIEnv *, jobject, jlong);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    timeouts
 * Signature: (JIIIII)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_timeouts
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    setEventMask
 * Signature: (JI)V
 */
JNIEXPORT void JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_setEventMask
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    waitEvent
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_waitEvent
  (JNIEnv *, jobject, jlong, jint);

/*
 * Class:     org_vesalainen_comm_channel_WinSerialChannel
 * Method:    doSelect
 * Signature: (ILjava/nio/LongBuffer;I)I
 */
JNIEXPORT jint JNICALL Java_org_vesalainen_comm_channel_WinSerialChannel_doSelect
  (JNIEnv *, jclass, jint, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
